### ISSUE TITLE
Replace mantid website landing page

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/roadmap#16]
**Summary**

The current landing page has a long history from when the project was originally started and was hosted in mediawiki. The project, and web technologies, have moved on from this and a rewrite of the site is long overdue. An additional motivation is that the sever where the current www.mantidproject.org is hosted no longer supports the libraries that the mediawiki runs on. This will move to a static site using similar technologies as the other subdomains in mantid.

**Intended outcome**

* There is a new landing page for www.mantidproject.org.
* That page summarizes the project and contains links to information in a clear way.
* Information will be added with the aim of meeting the [requirements of CII:FLOSS passing badge](https://bestpractices.coreinfrastructure.org/en/criteria/0) as appropriate.
* The new page will be written using python sphinx to allow for easier linking to other subdomains inside of mantid, make it simpler to have a consistent look and feel, and reduce the number of tools used by the project.

**Acceptance criteria**

The "old" site has been moved out of the way and users land at the new static page.

**How will it work?**

* skeleton new page will be created
* new page will be published via github pages so people can easily view the current state
* periodic updates will be sent to the steering committee with request for comment on particular potions
* no subdomains outside of `www` will be covered by these changes (e.g. docs.mantidproject.org will receive little change)

links: [old page](https://www.mantidproject.org/) and [dev version of new page](https://github.com/mantidproject/www.mantidproject.org/pull/4/files)

**Comment by martyngigg** [comment]
This is now live at mantidproject.org
