### ISSUE TITLE
SANS polarisation analysis - scripts

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/roadmap#25]
**Summary**

Mantid support is required for polarised SANS experiments at ISIS

**Intended outcome**

Users will be performing polarised SANS experiments at ISIS from late 2022. As a minimum, we need to provide scripts to support reduction of these experiments by this time. Users will require instrument scientists' help to use the scripts, so the longer term aim will be to provide GUI support, although that is beyond the scope of this initial issue.

**Acceptance criteria**

To be agreed

**How will it work?**

See [33638](https://github.com/mantidproject/mantid/issues/33638) for an ongoing discussion.

**Comment by sf1919** [comment]
After discussion at ISIS we have decided to remove this from the roadmap
