### ISSUE TITLE
SANS polarisation analysis - GUI support

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/roadmap#26]
**Summary**

Mantid support is required for polarised SANS experiments at ISIS.

**Intended outcome**

Following on from basic script support in #25, we also need to add full support to the ISIS SANS GUI to support polarised SANS experiments. This is needed so that users can perform all of their reductions from a unified interface, and are less reliant on instrument scientists' help. This will be required as soon as possible once users start running polarised SANS experiments in late 2022.

**Acceptance criteria**

To be agreed

**How will it work?**

See [33638](https://github.com/mantidproject/mantid/issues/33638) for an ongoing discussion.

**Comment by sf1919** [comment]
After discussion at ISIS we have decided to remove this from the roadmap
