### ISSUE TITLE
SANS tube calibration scripts

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/roadmap#27]
**Summary**

ISIS SANS have some historical tube calibration scripts that are essential to the reduction. The scripts need to be updated and tests added so that they can be maintained by the Mantid team. 

**Intended outcome**

The scripts currently need to be edited by users for each experiment, making them difficult to use and error-prone. They need to be parameterised to make usage easier and so that a canonical version of the scripts can be maintained. Tests need to be added to verify behaviour and ensure bugs are not introduced. The scripts are not well understood so this needs to be done before the original author retires at the end of 2022.

**Acceptance criteria**

To be agreed

**How will it work?**

See [33821](https://github.com/mantidproject/mantid/issues/33821) for a discussion

**Comment by sf1919** [comment]
After discussion at ISIS we have decided to remove this from the roadmap
