### ISSUE TITLE
Optimization of workflow with ALFView alignment tool

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/roadmap#29]
**Summary**

The [ALFView](https://docs.mantidproject.org/v6.5.0/interfaces/direct/ALF%20View.html#alf-view) tool is used by ISIS Excitations group for crystal alignment.

As the instrument itself is difficult to use the group have reported that the workflow within the tool needs improving to reduce frustration of the software for users.

**Intended Outcome & Acceptance Criteria**

Issue mantidproject/mantid#34558 describes the plan of action to tackle the usability issues. A minimal solution to consider this task complete is to implement the features describe and fix the bugs discovered.

**Comment by robertapplin** [comment]
The attached issue https://github.com/mantidproject/mantid/issues/34558 has been closed as completed
