### ISSUE TITLE
Improving tof powder diffraction calibration

### ISSUE THREAD

**Issue by zjmorgan** [mantidproject/roadmap#8]
**Summary**

Improvements for powder diffraction calibration at ORNL are being pursued. The overall procedure is to be divided into two steps: cross correlation and peak position calibration. The intent of cross correlation is to increase the sharpness of peaks through accumulation of statistics. Then the merged pixels are moved into their correct positions by multiple peaks fitting against nominal peak positions corresponding to standard diamond.

**Intended outcome**

The intent of this is to implement an improved approach for powder calibration that does automatic grouping of spectra based on DBSCAN and k-means clustering algorithms. The groups are then cross correlated to minimize the distance between spectra of each group. Finally, the groups of pixels are calibrated to the know calibration standard using diamond d-spacings.

**Acceptance criteria**

1. Automatic generation of a grouping file with spectra separated into different groups
2. Cross correlate group of pixels that minimizes distance between spectra
3. Calibrate the groups of pixels based on calibration standard

**How will it work?**

The clustering algorithms are to be implemented in a Python script within mantidtotalscattering. A second Mantid Python script  will load the mask and grouping files to perform the cross correlation. Finally, fitting is performed summing all spectra into a spectrum. A Mantid powder calibration is applied fitting multiple peaks to obtain a series of fitted peak positions. Then a single DIFC value is obtained from the fitted peak positions and the d-spacing values of standard diamond peaks.

**Comment by martyngigg** [comment]
As part of this I think you mentioned that you would need to be able to use `scikit-learn`? We will also have this requirement, along with `scikit-image`, for some upcoming work on implementing an improved algorithm for SX peak finding. It is based on the output of a project at ISIS to assess how ML can be used for this case and it was quite successful.

I'm going to add the peak finding item as a roadmap for 6.3 soon when we have a bit more detail but I thought it was worth raising that there is overlap on some requirements here.
